### ISSUE TITLE
Can you explain the complicated awk command in sysfs-reload file?

### ISSUE THREAD

**Issue by LinguineCode** [danfoster/puppet-sysfs#4]
Hello, thanks very much for your module. I used it today and it simply works.

This isn't an "issue" it's just a question which can perhaps lead to an improvement. What is this complicated awk command doing in [sysfs-reload file](https://github.com/danfoster/puppet-sysfs/blob/86df5ae/files/sysfs-reload)?

I'm asking because there are more modern tools, namely Puppet itself, that can probably be used with more clarity and visibility to write the `/etc/sysfs.conf` file. If I understood better then I would even to do the work and make a PR.

**Comment by danfoster** [comment]
I can try!

The problem was I couldn't find a way of making `sysfsutils` reload the `/etc/sysfs.conf` and apply the settings without a reboot. Therefore this is a workaround to parse the config file and set the values buy echoing them to the correct parts of the `/sys/` directly.

To break the line in to parts:

1.  `(\S+)\s*=(\S+)` is a regex using backreferences to store each side of a the equals sign in variables `$1` and `$2`. e.g, `class/block/sdb/queue/read_ahead_kb=8` in `/etc/sysfs.conf` would make `$1=class/block/sdb/queue/read_ahead_kb` and `$2=8`.
2. `cmd=sprintf("/bin/echo %s > /sys/%s",$2, $1)` sets the variable `cmd` with a valid shell command to set the sysfs setting. In our example `cmd` would be set to `/bin/echo 8 > /sys/class/block/sdb/queue/read_ahead_kb`
3. `system(cmd)` runs the command we've set in the `cmd` variable.

Since awk is a line parser, it does this for every line in `/etc/sysfs.conf`

Looking forward to see if you can find a better solution.

**Comment by LinguineCode** [comment]
Thanks for answering. I'm no longer using this module, the project got simplified, so this fell on the back burner for me. I will close this but keep it in mind for the future.
